WB* macros uses __func__ instead of __LINE__
The lineno is unstable. source code changes frequently.
function name is rather stable.

plus:
- fix error checks.

diff --git a/prepare b/prepare
--- a/prepare
+++ b/prepare
@@ -17,6 +17,11 @@ echo create writeboost-vol ...
 sz=`blockdev --getsize ${BACKING}`
 dmsetup create writeboost-vol --table "0 ${sz} writeboost ${BACKING} ${CACHE} 7"
 
+if test $? -ne 0; then
+    echo "initialization failed. see dmseg"
+    exit
+fi
+
 echo configure things for tests ...
 dmsetup message writeboost-vol 0 enable_migration_modulator 1
 dmsetup message writeboost-vol 0 update_record_interval 2
